crud creation for reviews routes
Armax7/Lotus pull request #111
Opened 2023-04-15 13:22 UTC by MaxiPogonza

BE - 122 Crear rutas para review donde se pueda modificar, postear, obtener y eliminar datos

2023-04-15 13:23 UTC, MaxiPogonza commented
![](https://github.trello.services/images/mini-trello-icon.png) [BE - 122 Crear rutas para review donde se pueda modificar, postear, obtener y eliminar datos](https://trello.com/c/QGRp1r9h/158-be-122-crear-rutas-para-review-donde-se-pueda-modificar-postear-obtener-y-eliminar-datos)

2023-04-15 15:26 UTC, Armax7 requested changes
- [ ] Replace Query for Body on Setters (POST, PUT, DELETE)
- [ ] Create a general Getter aside from only using query

2023-04-15 21:56 UTC, Marindala approved these changes

2023-04-15 23:08 UTC, Colifaa approved these changes

2023-04-15 23:12 UTC, Armax7 approved these changes

2023-04-16 00:36 UTC, gekoJs approved these changes

2023-04-16 15:38 UTC, merged